from .acceso_model import Acceso as Acceso
from .biometria_cliente_model import Biometria_Cliente as Biometria_Cliente
from .categoria_maquina_model import Categoria_Maquina as Categoria_Maquina
from .cliente_model import Cliente as Cliente
from .disciplina_model import Disciplina as Disciplina
from .entrenador_model import Entrenador as Entrenador
from .lote_producto_model import Lote_Producto as Lote_Producto
from .maquina_model import Maquina as Maquina
from .membresia_model import Membresia as Membresia
from .pago_membresia_model import Pago_Membresia as Pago_Membresia
from .plan_model import Plan as Plan
from .producto_model import Producto as Producto
from .reserva_model import Reserva as Reserva
from .rol_model import Rol as Rol
from .sesion_model import Sesion as Sesion
from .ticket_mantenimiento_model import Ticket_Mantenimiento as Ticket_Mantenimiento
from .usuario_model import Usuario as Usuario
from .venta_detalle_model import Venta_Detalle as Venta_Detalle
from .venta_tienda_model import Venta_Tienda as Venta_Tienda
